version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3307:3306
#    environment:
#      MYSQL_DATABASE: hops_db
#      MYSQL_ROOT_PASSWORD: thymmz22
#      MYSQL_DDL: update
#      MYSQL_DIALECT: org.hibernate.dialect.MySQL5Dialect
#      MYSQL_INIT: always
#      IBM_QM: mq
#      IBM_CHANNEL: "DEV.ADMIN.SVRCONN"
#      IBM_CONNAME: 169.60.46.60(1414)
#      IBM_USER: admin
#      IBM_PASSWORD: Miracle@1234

  springboot-fqd:
    image: springboot-fqd
    restart: always
    build: .
    ports:
      - 9043:9041
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/hops_db
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: thymmz22
      MYSQL_PORT: 3306
      #CSV_FILE: file:src/main/resources/files?noop=true
#    configs:
#      - ibm-config
    depends_on:
      - mysqldb
    volumes:
      - /src/main/resources/files: /var/lib/mysql/data

#  configs:
#    ibm-config:
#      external: true
volumes:
  - /src/main/resources/files: /var/lib/mysql/data