version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: hops_db
      MYSQL_ROOT_PASSWORD: thymmz22
      MYSQL_DDL: create
      MYSQL_DIALECT: org.hibernate.dialect.MySQL5Dialect
      MYSQL_INIT: always

  springboot-fqd:
    image: springboot-fqd
    build: .
    ports:
      - 9063:9061
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: thymmz22
      MYSQL_PORT: 3306
      CSV_FILE: file:var/lib/csvdata?noop=true
    depends_on:
      - mysqldb
